AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Stack for managing jenkins storage.
Parameters:
  ParentAlertStack:
    Description: >-
      Name of the parent Stack containing the Alert topic. The Stack
      is queried for the '-TopicArn' export.
    Type: String
    Default: ''
  ParentVpcStack:
    Description: >-
      Name of the parent Stack containing the VPC. The Stack is
      queried for the '-AvailabilityZone' export.
    Type: String
  VolumeType:
    Description: >-
      The volume type. This can be gp2 for General Purpose SSD, io1
      for Provisioned IOPS SSD, st1 for Throughput Optimized HDD, sc1
      for Cold HDD, or standard for Magnetic volumes.
    Type: String
    AllowedValues: [standard, io1, gp2, sc1, st1]
    Default: standard
  Iops:
    Description: >-
      The desired amount of I/O operations per seconds. Only use for
      certain volume types.
    Type: String
    Default: ''
  Size:
    Description: The size of the volume, in gibibytes.
    Type: Number
    Default: 50
Conditions:
  HasAlertTopic:
    !Not [!Equals [!Ref ParentAlertStack, '']]
Resources:

  Storage:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone:
        Fn::ImportValue:
          !Sub '${ParentVpcStack}-AvailabilityZone'
      Encrypted: false
      Iops: !Ref Iops
      VolumeType: !Ref VolumeType
      Size: !Ref Size
      Tags:
      - Key: Name
        Value: !Ref AWS::StackId
      - Key: Content
        Value: jenkins-home

  StorageBurstCreditBalanceTooLowAlarm:
    Condition: HasAlertTopic
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: >-
        Volume is running out of burst credeits. Expect a significant
        performance drop.
      Namespace: AWS/EBS
      MetricName: BurstBalance
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 40
      AlarmActions:
      - Fn::ImportValue: !Sub '${ParentAlertStack}-TopicArn'
      Dimensions:
      - Name: VolumeId
        Value: !Ref Storage

Outputs:
  VolumeId:
    Description: Logical Id of the EBS volume
    Value: !Ref Storage
    Export:
      Name: !Sub '${AWS::StackName}-VolumeId'
