AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Stack for managing a Route53 domain.
Parameters:
  Domain:
    Description: The name of the domain for which to create a zone.
    Type: String
    AllowedPattern: "[a-z0-9.]+"
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneTags:
      -  Key: Name
         Value: !Ref AWS::StackId
      Name: !Ref Domain

Outputs:
  ZoneId:
    Description: Logical ID of the HostedZone
    Value: !Ref HostedZone
  NameServers:
    Description: Nameservers for the HostedZone
    Value: !Join [", ", !GetAtt HostedZone.NameServers]
